name: Simpan Naskah Jurnal

on:
  workflow_dispatch:
    inputs:
      judul:
        description: 'Judul Artikel'
        required: true
      konten:
        description: 'Isi naskah lengkap (Markdown or HTML)'
        required: true

permissions:
  contents: write

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Simpan naskah ke file
        run: |
          mkdir -p naskah
          echo "${{ github.event.inputs.konten }}" > naskah/"${{ github.event.inputs.judul }}.md"

      - name: Commit & push hasil
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add naskah/"${{ github.event.inputs.judul }}.md"
          git commit -m "Menambahkan naskah ${{ github.event.inputs.judul }}"
          git push
